# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-27 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminname', models.CharField(max_length=32, verbose_name='用户名')),
                ('adminpassword', models.CharField(help_text='input password', max_length=64)),
            ],
        ),
    ]
