# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-28 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAdmin', '0002_useradmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='dept',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
