# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-30 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAdmin', '0003_usergroup_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='phone',
            field=models.IntegerField(default=8868, max_length=32),
        ),
    ]
