# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-30 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAdmin', '0004_auto_20181130_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(default=8868, max_length=32),
        ),
    ]
