# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-30 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserAdmin', '0006_auto_20181130_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='UserAdmin.UserGroup'),
        ),
    ]
